stages:
  - sync
  - deadlines
  - plagiates

before_script:
  - cp python-gitlab.cfg $HOME/.python-gitlab.cfg
  - echo "private_token = ${PRIVATE_API_TOKEN}" >> $HOME/.python-gitlab.cfg
  - pip install -r requirements.txt

create_tags:
  image: python:3
  stage: deadlines
  only:
    - master

  tags:
    - abgabesystem

  script:
    - python abgabesystem.py deadlines

sync_students:
  image: python:3
  stage: sync
  only:
    - master

  tags:
    - abgabesystem

  script:
    - python abgabesystem.py sync