stages:
  - deadlines
  - plagiates

create_tags:
  image: python:3
  stage: deadlines
  only:
    - master

  tags:
    - abgabesystem

  script:
    - cp python-gitlab.cfg $HOME/.python-gitlab.cfg
    - echo "private_token = ${PRIVATE_API_TOKEN}" >> $HOME/.python-gitlab.cfg
    - pip install -r requirements.txt
    - python abgabesystem.py deadlines
