stages:
  - deadlines
  - plagiates

create_tags:
  image: python:3
  stage: deadlines
  only:
    - master

  tags:
    - abgabesystem

  script:
    - echo "private_token = ${PRIVATE_API_TOKEN}" >> $HOME/.python-gitlab.cfg
    - pip install python-gitlab
    - ./abgabesystem.py deadlines
