ldap:
  basedn: "ou=people,dc=tu-bs,dc=de"
  provider: main
courses:
  - !!python/object:abgabesystem.Course
    name: Programmieren 1
    base: programmieren_1_solutions
    plagiates: programmieren_1_abgabesystem
    students: List_of_groups_Lecture_Programmieren_1.csv
    deadlines:
      - !!python/object:abgabesystem.Deadline
        tag: test
        time: !!timestamp 2018-04-18
        ref: master
      - !!python/object:abgabesystem.Deadline
        tag: blatt1
        time: !!timestamp 2018-04-29
        ref: master
  - !!python/object:abgabesystem.Course
    name: Programmieren 2
    base: programmieren_2_solutions
    plagiates: programmieren_2_abgabesystem

    students: List_of_groups_Lecture_Programmieren_2.csv
    deadlines:
      - !!python/object:abgabesystem.Deadline
        tag: Test
        time: !!timestamp 2018-04-19
        ref: master
