---
!!Course
name: Programmieren 1
base: solutions
ldap:
  basedn: "ou=people,dc=tu-bs,dc=de"
  provider: main
deadlines:
  -
    !!Deadline
    tag: Exercise 1
    time: 2018-04-01t00:00.00
    ref: master

  -
    !!Deadline
    tag: Exercise 2
    time: 2018-04-15t15:00.00
    ref: master
        
